/**
 * Facility configuration.
 * meshName must exactly match the node name in the GLTF scene graph
 * as exported from Blender.
 */
export const BUILDINGS = [
  {
    meshName: 'Apothiki_1',
    name: 'Apothiki 1',
    category: 'Tool Storage',
    icon: '',
    hours: 'Mon – Fri: 07:00 – 17:00',
    description: 'Primary storage facility for mining hand tools and small equipment. Houses drills, pickaxes, shovels, safety gear, and personal protective equipment (PPE) issued to site personnel.',
    contact: '+30 210 000 0001',
    photo: null,
  },
  {
    meshName: 'Apothiki_2',
    name: 'Apothiki 2',
    category: 'Maintenance Equipment',
    icon: '',
    hours: 'Mon – Fri: 07:00 – 17:00',
    description: 'Storage and staging area for heavy maintenance equipment. Contains hydraulic lifts, spare parts for excavators and haul trucks, welding units, and scheduled servicing supplies for on-site machinery.',
    contact: '+30 210 000 0002',
    photo: null,
  },
  {
    meshName: 'Apothiki_3',
    name: 'Apothiki 3',
    category: 'Materials & Consumables',
    icon: '',
    hours: 'Mon – Fri: 07:00 – 17:00',
    description: 'Storage of operational consumables including lubricants, hydraulic fluids, blasting accessories, safety signage, and replacement parts for conveyor and crushing systems.',
    contact: '+30 210 000 0003',
    photo: null,
  },
  {
    meshName: 'Kaminada',
    name: 'Kaminada',
    category: 'Processing Stack',
    icon: '',
    hours: 'Continuous Operation',
    description: 'Main processing and ventilation stack of the open pit facility. Manages exhaust emissions from ore processing operations and serves as a reference landmark for site navigation and aerial surveys.',
    contact: '+30 210 000 0004',
    photo: null,
  },
  {
    meshName: 'big_rock_pile',
    name: 'Gravel',
    category: 'Coarse Aggregate · 20–63 mm',
    icon: '',
    hours: 'Continuous Operation',
    description: 'Stockpile of coarse crushed rock aggregate. Primary structural ingredient for concrete mixes (C25/30 and above) and road-base layers. Sourced directly from the primary crusher and graded on-site.',
    contact: '+30 210 000 0005',
    photo: null,
    granulometry: [
      { sieve: '63 mm',   passing: 100 },
      { sieve: '50 mm',   passing: 95  },
      { sieve: '31.5 mm', passing: 72  },
      { sieve: '20 mm',   passing: 8   },
      { sieve: '10 mm',   passing: 2   },
    ],
  },
  {
    meshName: 'medium_rock_pile',
    name: 'Pea Gravel',
    category: 'Medium Aggregate · 10–20 mm',
    icon: '',
    hours: 'Continuous Operation',
    description: 'Stockpile of medium-grade crushed stone aggregate. Used in standard concrete formulations (C20/25) and drainage layer fill. Blended with coarse and fine aggregates to achieve target strength grades.',
    contact: '+30 210 000 0006',
    photo: null,
    granulometry: [
      { sieve: '25 mm',   passing: 100 },
      { sieve: '20 mm',   passing: 98  },
      { sieve: '16 mm',   passing: 75  },
      { sieve: '12.5 mm', passing: 40  },
      { sieve: '10 mm',   passing: 8   },
      { sieve: '8 mm',    passing: 2   },
    ],
  },
  {
    meshName: 'filler_pile',
    name: 'Filler',
    category: 'Mineral Filler · <0.063 mm',
    icon: '',
    hours: 'Continuous Operation',
    description: 'Fine mineral filler stockpile. Improves workability, reduces voids, and enhances durability in concrete mix designs. Also used as supplementary cementitious material to partially replace cement content.',
    contact: '+30 210 000 0007',
    photo: null,
    granulometry: [
      { sieve: '0.5 mm',   passing: 100 },
      { sieve: '0.25 mm',  passing: 99  },
      { sieve: '0.125 mm', passing: 92  },
      { sieve: '0.063 mm', passing: 80  },
    ],
  },
  {
    meshName: 'Sand_Pile',
    name: 'Sand',
    category: 'Fine Aggregate · 0–5 mm',
    icon: '',
    hours: 'Continuous Operation',
    description: 'Natural and processed sand stockpile. Essential fine aggregate for concrete and mortar production. Graded to meet EN 12620 specifications for construction-grade concrete mixes.',
    contact: '+30 210 000 0008',
    photo: null,
    granulometry: [
      { sieve: '5 mm',    passing: 100 },
      { sieve: '2 mm',    passing: 88  },
      { sieve: '1 mm',    passing: 72  },
      { sieve: '0.5 mm',  passing: 52  },
      { sieve: '0.25 mm', passing: 28  },
      { sieve: '0.125 mm',passing: 10  },
      { sieve: '0.063 mm',passing: 3   },
    ],
  },
];
